app/__init__.py
# Import flask and template operators
from flask import Flask, render_template, redirect, url_for, request

# Define the WSGI application object
app = Flask(__name__)

# Configurations
app.config.from_object('config')

# Import a module/component using its blueprint handler variable
from app.arrondissment_traffic.controllers import arrondissment_traffic
from app.population.controllers import population
# Register blueprint(s)
app.register_blueprint(arrondissment_traffic, url_prefix='/arr_traffic')
app.register_blueprint(population, url_prefix='/population')

# Sample HTTP error handling
@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404

@app.route('/')
def index():
	return redirect(url_for('arrondissment_traffic.index'))

app/arrondissment_traffic/controllers.py
import pandas as pd
import numpy as np
# Import flask dependencies
from flask import Blueprint, request, render_template, g, redirect, url_for, jsonify
from collections import OrderedDict
import datetime

# Define the blueprint arrondissment_traffic
arrondissment_traffic = Blueprint('arrondissment_traffic', __name__)

@arrondissment_traffic.route('/', methods=['GET', 'POST'])
def index():
    return render_template('arrondissment_traffic/arr_traffic.html')

@arrondissment_traffic.route('/getDateSliderValues', methods=['POST'])
def getDateSliderValues():
	direction = request.form['direction']
	month = request.form['month']
	month_raw = request.form['month_raw']
	date_filter = request.form['date_filter']

	if direction == 'out':
		file_name = 'outgoing_traffic_per_arrondissment_' + month + '.csv'
	else:
		file_name = 'incoming_traffic_per_arrondissment_' + month + '.csv'

	csv_file = 'app/static/data_processed/arr_traffic/' + file_name
	df = pd.read_csv(csv_file)

	if date_filter == 'day':
		df['date_index'] = pd.to_datetime(df['timestamp'])
		df['month'] = df['date_index'].dt.month
		filtered_res = df['timestamp'][df.month == int(month_raw)].values.tolist()
		result = []

		for date in filtered_res:
			split_values = date.split(' ')
			result.append(split_values[0])

		result = OrderedDict.fromkeys(result).keys()

	else:
		df = pd.read_csv(csv_file)
		result = pd.unique(df.timestamp.ravel()).tolist()

	return jsonify(result=result)

@arrondissment_traffic.route('/getTrafficData', methods=['POST'])
def getTrafficData():
	direction = request.form['direction']
	traffic = request.form['traffic']
	month = request.form['month']
	month_raw = request.form['month_raw']
	date_filter = request.form['date_filter']
	date = request.form['date']

	file_name = ''
	column = ''

	if direction == 'out':
		file_name = 'outgoing_traffic_per_arrondissment_' + month + '.csv'
		if traffic == 'call_dur':
			column = 'total_outgoing_call_duration'
		else:
			column = 'number_of_outgoing_calls'
	else:
		file_name = 'incoming_traffic_per_arrondissment_' + month + '.csv'
		if traffic == 'call_dur':
			column = 'total_incoming_call_duration'
		else:
			column = 'number_of_incoming_calls'

	csv_file = 'app/static/data_processed/arr_traffic/' + file_name
	df = pd.read_csv(csv_file)

	if date_filter == 'hour':
		result = df[['arr_id', column]][df.timestamp == date].sort(column, ascending=1)
	elif date_filter == 'day':
		# pass
		df['date_index'] = pd.to_datetime(df['timestamp'])
		df['day'] = df['date_index'].dt.day
		day = datetime.datetime.strptime(date, '%Y-%m-%d').date().day
		result = df[df.day == day]\
			.groupby(['arr_id'], as_index=False)\
			.agg({column: np.sum})\
			.sort(column, ascending=1)
	else:
		result = df.groupby(['arr_id'], as_index=False)\
			.agg({column: np.sum})\
			.sort(column, ascending=1)

	result = normalizeData(result)

	return jsonify(result=result)

def normalizeData(data):
	data = data.values.tolist()
	list_length = len(data)
	min_val = data[0][1]
	max_val = data[list_length - 1][1]

	for i in range(len(data)):
		data[i][1] = float(data[i][1] - min_val) / float(max_val - min_val)

	return data

app/population/controllers.py
import pandas as pd
import numpy as np
# Import flask dependencies
from flask import Blueprint, request, render_template, g, redirect, url_for, jsonify

# Define the blueprint population
population = Blueprint('population', __name__)

@population.route('/')
def index():
	return redirect(url_for('population.per_arr'))

@population.route('/per_arr/', methods=['GET', 'POST'])
def per_arr():
    return render_template('population/per_arr.html')

@population.route('/per_region/', methods=['GET', 'POST'])
def per_region():
	return render_template('population/per_region.html')

@population.route('/per_square_km/', methods=['GET', 'POST'])
def per_square_km():
	return render_template('population/per_square_km.html')

@population.route('/per_arr/getPopulationData', methods=['GET'])
def getPopulationData():
	residents_file = 'app/static/data_processed/population/population_residents.csv'
	employees_file = 'app/static/data_processed/population/population_employees.csv'
	residents = pd.read_csv(residents_file).sort('arr_id', ascending=1)
	employees = pd.read_csv(employees_file).sort('arr_id', ascending=1)
	result = {'residents': residents.values.tolist(), 'employees': employees.values.tolist()}

	return jsonify(result)

@population.route('/per_region/getRegionPopulationData', methods=['GET'])
def getRegionPopulationData():
	residents_file = 'app/static/data_processed/population/population_residents.csv'
	employees_file = 'app/static/data_processed/population/population_employees.csv'
	senegal_arr_file = 'app/static/senegal_map/SENEGAL_ARR_V2.csv'
	senegal_reg_file = 'app/static/senegal_map/SENEGAL_REGIONS.csv'

	senegal_arr = pd.read_csv(senegal_arr_file)
	senegal_reg = pd.read_csv(senegal_reg_file)
	senegal = pd.merge(senegal_arr, senegal_reg, how='left', on=['REG', 'REG'])

	residents = pd.read_csv(residents_file).sort('arr_id', ascending=1)
	employees = pd.read_csv(employees_file).sort('arr_id', ascending=1)

	residents = residents.merge(
			senegal,
			left_on='arr_id',
			right_on='ARR_ID',
			how='left')

	employees = employees.merge(
			senegal,
			left_on='arr_id',
			right_on='ARR_ID',
			how='left')

	residents = residents.groupby(['REG_ID'], as_index=False)\
		.agg({'number_of_residents': np.sum, 'number_of_residents_in_percents': np.sum})
	residents['number_of_residents_in_percents'] = residents['number_of_residents_in_percents'].apply(lambda x: round(x, 2))

	employees = employees.groupby(['REG_ID'], as_index=False)\
		.agg({'number_of_employees': np.sum, 'number_of_employees_in_percents': np.sum})
	employees['number_of_employees_in_percents'] = employees['number_of_employees_in_percents'].apply(lambda x: round(x, 2))

	result = {'residents': residents.values.tolist(), 'employees': employees.values.tolist()}

	return jsonify(result)

@population.route('/per_square_km/calcPopulationPerSquareKm', methods=['GET'])
def calcPopulationPerSquareKm():
	residents_file = 'app/static/data_processed/population/population_residents.csv'
	employees_file = 'app/static/data_processed/population/population_employees.csv'
	senegal_arr_file = 'app/static/senegal_map/SENEGAL_ARR_V2.csv'
	senegal_reg_file = 'app/static/senegal_map/SENEGAL_REGIONS.csv'

	senegal_arr = pd.read_csv(senegal_arr_file)
	senegal_reg = pd.read_csv(senegal_reg_file)
	senegal = pd.merge(senegal_arr, senegal_reg, how='left', on=['REG', 'REG'])

	residents = pd.read_csv(residents_file).sort('arr_id', ascending=1)
	employees = pd.read_csv(employees_file).sort('arr_id', ascending=1)

	residents = residents.merge(
			senegal,
			left_on='arr_id',
			right_on='ARR_ID',
			how='left')

	employees = employees.merge(
			senegal,
			left_on='arr_id',
			right_on='ARR_ID',
			how='left')

	# calculate residents density
	residents = residents.groupby(['REG_ID'], as_index=False)\
		.agg({'number_of_residents': np.sum, 'number_of_residents_in_percents': np.sum})

	residents = residents.merge(
			senegal_reg,
			left_on='REG_ID',
			right_on='REG_ID',
			how='left')

	density = residents.apply(calc_density, axis=1)
	residents['density'] = density
	residents = residents.sort('density', ascending=1)
	
	return jsonify(result=residents.values.tolist())

def calc_density(group):
	area = group['AREA']
	residents_num = group['number_of_residents']

	return residents_num / area

app/templates/arrondissment_traffic/arr_traffic.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}

    <script type="text/javascript" src="{{ url_for('static', filename='js/arrondissment_traffic/arr_traffic.js') }}"></script>
{% endblock %}
{% block content %}	
	<div class="col-md-7">
	    <div id="map_container"></div>
	</div>
	<div class="col-md-5">
	    <div id="controls">
	        <h2>Options</h2>
	        <form class="form-horizontal">
	        	<!-- Type of Traffic -->
	            <div class="form-group">
	                <label for="traffic" class="col-sm-3 control-label">Type of Traffic:</label>
	                <div class="col-sm-5">
	                    <select id="traffic" class="form-control">
	                        <option value="num_calls">Number of calls</option>
	                        <option value="call_dur">Total call duration</option>
	                    </select>
	                </div>
	            </div>

	            <!-- Traffic Direction -->
	            <div class="form-group">
	                <label for="direction" class="col-sm-3 control-label">Traffic Direction:</label>
	                <div class="col-sm-5">
	                    <select id="direction" class="form-control">
	                        <option value="out">Outgoing</option>
	                        <option value="in">Incoming</option>
	                    </select>
	                </div>
	            </div>

	            <!-- Choose Date Filter -->
	            <div class="form-group">
	                <label for="date_filter" class="col-sm-3 control-label">Filter Date:</label>
	                <div class="col-sm-5">
	                    <select id="date_filter" class="form-control">
							<option value="hour">By Hour</option>
							<option value="day">By Day</option>
							<option value="month">By Month</option>
	                    </select>
	                </div>
	            </div>

	            <!-- Choose Month -->
	            <div id="choose_month_wrap" class="form-group">
	                <label for="month" class="col-sm-3 control-label">Choose Month:</label>
	                <div class="col-sm-5">
	                    <select id="month" class="form-control">
							<option value="01" data-raw="1">January</option>
							<option value="02" data-raw="2">February</option>
							<option value="03" data-raw="3">March</option>
							<option value="04" data-raw="4">April</option>
							<option value="05" data-raw="5">May</option>
							<option value="06" data-raw="6">June</option>
							<option value="07" data-raw="7">July</option>
							<option value="08" data-raw="8">August</option>
							<option value="09" data-raw="9">September</option>
							<option value="10" data-raw="10">October</option>
							<option value="11" data-raw="11">November</option>
							<option value="12" data-raw="12">December</option>
	                    </select>
	                </div>
	            </div>

	            <!-- Choose date -->
	            <div class="form-group">
	                <label for="choose_date" class="col-sm-3 control-label">Choose date:</label>
	                <div class="col-sm-6">
	                    <div id="choose_date"></div>
	                </div>
	            </div>

	            <div class="form-group">
	                <label for="choose_date" class="col-sm-3 control-label">Selected date:</label>
	                <div class="col-sm-5">
	                    <input id="selected_date" type="text" class="form-control" placeholder="Text input" disabled>
	                </div>
	            </div>

				<div class="form-group">
					<div class="col-sm-offset-3 col-sm-6">
						<div class="checkbox">
							<label>
								<input id="autoplay" type="checkbox"> Autoplay
							</label>
						</div>
					</div>
				</div>
	        </form>
	    </div>
	</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head %}
        <title>D4D Senegal</title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lib/jquery-ui-1.11.4/jquery-ui.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lib/bootstrap-3.3.5-dist/css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/d3.v3.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/topojson.v1.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/jquery.2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/jquery-ui.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/datamaps.world.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/bootstrap.min.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('static', filename='js/lib/rainbowvis.js') }}"></script>

        <script type="text/javascript">
            // http://flask.pocoo.org/docs/0.10/api/#flask.Request.path
            var $SCRIPT_ROOT = {{ request.base_url|tojson|safe }};
            var $GEOJSON_FILE = '/static/senegal_map/senegal_geojson.json';
            var $GEOJSON_REGIONS_FILE = '/static/senegal_map/senegal_regions_geojson.json';
            var $TOPOJSON_FILE = '/static/senegal_map/senegal_topojson.json';
            var $TOPOJSON_REGIONS_FILE = '/static/senegal_map/senegal_regions_topojson.json';
            console.log($SCRIPT_ROOT);

            $(function() {
                window.selectMenuItem = function(menu_item_id) {
                    $('.menu_item').removeClass('active');
                    $('#' + menu_item_id).addClass('active');
                }
            });
        </script>        
    {% endblock %}
</head>
<body>
    <div id="loading" class="loading_background hidden">
        <div class="spinner">
            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="loader_text">Loading</div>
        </div>
    </div>

    <div class="container-fluid fill">
        <!-- menu -->
        <div class="row">
            <nav class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="#">D4D Senegal</a>
                            </div>

                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-right">
                                    <li id="menu_arr_traffic" class="menu_item">
                                        <a href="{{url_for('arrondissment_traffic.index')}}">Arrondissment Traffic</a>
                                    </li>
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Population <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li id="menu_per_arr" class="menu_item">
                                                <a href="{{url_for('population.per_arr')}}">Per Arrondissment</a>
                                            </li>
                                            <li id="menu_per_region" class="menu_item">
                                                <a href="{{url_for('population.per_region')}}">Per Region</a>
                                            </li>
                                            <li id="menu_per_square_km" class="menu_item">
                                                <a href="{{url_for('population.per_square_km')}}">Per Square Kilometer</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="menu_item"><a href="#">Link</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>                
                </div>
            </nav>
        </div>

        <!-- map -->
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

app/templates/population/per_arr.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}

    <script type="text/javascript" src="{{ url_for('static', filename='js/population/per_arr.js') }}"></script>
{% endblock %}
{% block content %}
	<div class="col-md-7">
	    <div id="map_container"></div>
	</div>
	<div class="col-md-5">

		<fieldset>
			<p>This map shows the number of residents against the number of employees per arrondissment.</p>
			<legend>Population:</legend>

			No. of Residents is Greater then No. of Employees: <div id="red_gradient"></div>
			No. of Residents is Less then No. of Employees: <div id="green_gradient"></div>
			No. of Residents is Equal to No. of Employees: <div id="blue_gradient"></div>
		</fieldset>
	</div>
{% endblock %}

app/templates/population/per_region.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}

    <script type="text/javascript" src="{{ url_for('static', filename='js/population/per_region.js') }}"></script>
{% endblock %}
{% block content %}
	<div class="col-md-7">
		<div id="map_container"></div>
	</div>
	<div class="col-md-5">
		<fieldset>
			<p>This map shows the number of residents against the number of employees per region.</p>
			<legend>Population:</legend>

			No. of Residents is Greater then No. of Employees: <div id="green_gradient"></div>
			No. of Residents is Less then No. of Employees: <div id="red_gradient"></div>
			No. of Residents is Equal to No. of Employees: <div id="blue_gradient"></div>
		</fieldset>
	</div>
{% endblock %}

app/templates/population/per_square_km.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}

    <script type="text/javascript" src="{{ url_for('static', filename='js/population/per_square_km.js') }}"></script>
{% endblock %}
{% block content %}
	<div class="col-md-7">
		<div id="map_container"></div>
	</div>
	<div class="col-md-5">
		<fieldset>
			<p>This map shows the number of residents per square kilometer per region.</p>
			<legend>Population:</legend>
			Population Density: <div id="default_gradient"></div>
		</fieldset>
	</div>
{% endblock %}